package database;
import bus.ticket.reservation.system.adminHome;
import java.sql.*;
import java.util.*;
import java.awt.*;  
import javax.swing.*;    
import javax.swing.event.*; 
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Avishek Saha
 */
public class bus_details extends javax.swing.JFrame {

    /**
     * Creates new form bus_details
     */
    save s;
    public bus_details(save s) {
        this.s=s;
        initComponents();
        showBuses();
    }
    
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/btrs", "root","");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

    
    public ArrayList<Bus> getBus(){ 
	
		ArrayList<Bus> buses	= new ArrayList<Bus>();
		Connection con = getConnection();
		
		Statement stat;
		ResultSet rs;
		Bus b;
	
	try{
		stat = con.createStatement();
		String sql="select * from bus_details";
		rs= stat.executeQuery(sql);
		
		while(rs.next()){
			
			b = new Bus(
			     rs.getInt("id"),
				  rs.getString("name"),
				  rs.getString("source"),
				  rs.getString("destination"),
				  rs.getString("type"),
				  rs.getString("departure"),
				  rs.getString("arrival"),
				  rs.getInt("seats_available"),
				  rs.getInt("fare"),
                                rs.getString("date")
			);
			
			buses.add(b);
		}
	}
	catch (Exception e) {
            e.printStackTrace();          
        }
		
	
	return buses;
}
    
    /**
     *
     */
    public void showBuses()
    {
        ArrayList<Bus> list = getBus();
        DefaultTableModel model = (DefaultTableModel)table_busDetails.getModel();
        
        Object[] row = new Object[10];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getId();
             row[1] = list.get(i).getName();
              row[2] = list.get(i).getSource();
               row[3] = list.get(i).getDestination();
	        row[4] = list.get(i).getType();
	         row[5] = list.get(i).getDeparture();
		  row[6] = list.get(i).getArrival();
		   row[7] = list.get(i).getSeatsAvailable();
		    row[8] = list.get(i).getFare();
                     row[9]=list.get(i).getDate();
                                    
           
           model.addRow(row);
       }
    }
    
    public void executeSQLquery(String query, String message)
    {
        Connection con = getConnection();
        Statement stat;
        try{
            stat = con.createStatement();
            if((stat.executeUpdate(query)) == 1)
            {
                //refresh jTable data
                DefaultTableModel model =  (DefaultTableModel)table_busDetails.getModel();
                model.setRowCount(0);
                showBuses();
                
                JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
            }else{
                 JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        }catch(Exception ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_seatsAvailable = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_source = new javax.swing.JLabel();
        l_destination = new javax.swing.JLabel();
        l_fair = new javax.swing.JLabel();
        l_busID = new javax.swing.JLabel();
        l_departure = new javax.swing.JLabel();
        l_arrival = new javax.swing.JLabel();
        l_type = new javax.swing.JLabel();
        t_busID = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_source = new javax.swing.JTextField();
        t_destination = new javax.swing.JTextField();
        t_type = new javax.swing.JTextField();
        t_departure = new javax.swing.JTextField();
        t_arrival = new javax.swing.JTextField();
        t_seatsAvailable = new javax.swing.JTextField();
        t_fare = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_busDetails = new javax.swing.JTable();
        t_update = new javax.swing.JButton();
        t_delete = new javax.swing.JButton();
        b_add = new javax.swing.JButton();
        b_back = new javax.swing.JButton();
        l_date = new javax.swing.JLabel();
        t_date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l_seatsAvailable.setText("Seats Available");

        l_name.setText("Name");

        l_source.setText("Source");

        l_destination.setText("Destination");

        l_fair.setText("Fare");

        l_busID.setText("Bus ID");

        l_departure.setText("Departure");

        l_arrival.setText("Arrival");

        l_type.setText("Type");

        t_busID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_busIDActionPerformed(evt);
            }
        });

        table_busDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "Bus Name", "Source", "Destination", "Type", "Departure", "Arrival", "Seats Available", "Fair", "Date"
            }
        ));
        table_busDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_busDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_busDetails);

        t_update.setText("UPDATE");
        t_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_updateActionPerformed(evt);
            }
        });

        t_delete.setText("DELETE");
        t_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_deleteActionPerformed(evt);
            }
        });

        b_add.setText("ADD");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });

        b_back.setText("BACK");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        l_date.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l_source, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_fair, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_destination, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(l_departure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_destination, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_departure)
                                    .addComponent(t_arrival)
                                    .addComponent(t_type)
                                    .addComponent(t_busID)
                                    .addComponent(t_name)
                                    .addComponent(t_source)
                                    .addComponent(t_fare)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l_seatsAvailable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_seatsAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(b_add, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(t_date)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_update, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(t_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_busID)
                            .addComponent(l_busID, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_name))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_source, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_source))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_destination))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_type))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_departure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_arrival))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_seatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_seatsAvailable))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_fair, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_fare))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_date))
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_add, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_busIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_busIDActionPerformed
      
    }//GEN-LAST:event_t_busIDActionPerformed

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        // TODO add your handling code here:
         String query = "INSERT INTO `bus_details`(`id`, `name`, `source`, `destination`, `type`, `departure`, `arrival`, `seats_available`, `fare`, `date`) VALUES ('"+t_busID.getText()+"', '"+t_name.getText()+"','"+t_source.getText()+"','"+t_destination.getText()+"','"+t_type.getText()+"','"+t_departure.getText()+"','"+t_arrival.getText()+"','"+t_seatsAvailable.getText()+"','"+t_fare.getText()+"', '"+t_date.getText()+"')";
           executeSQLquery(query, "ADDED");
         
        
    }//GEN-LAST:event_b_addActionPerformed

    private void table_busDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_busDetailsMouseClicked
        // Display Selected Row in JTextFields
        int i = table_busDetails.getSelectedRow();
        TableModel model = table_busDetails.getModel();
        
        t_busID.setText(model.getValueAt(i,0).toString());
        t_name.setText(model.getValueAt(i,1).toString());
        t_source.setText(model.getValueAt(i,2).toString());
        t_destination.setText(model.getValueAt(i,3).toString());
        t_type.setText(model.getValueAt(i,4).toString());
        t_departure.setText(model.getValueAt(i,5).toString());
        t_arrival.setText(model.getValueAt(i,6).toString());
        t_seatsAvailable.setText(model.getValueAt(i,7).toString());
        t_fare.setText(model.getValueAt(i,8).toString());
         t_date.setText(model.getValueAt(i,9).toString());
        
    }//GEN-LAST:event_table_busDetailsMouseClicked

    private void t_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_updateActionPerformed
        String query = "UPDATE `bus_details` SET `name`= '"+t_name.getText()+"',`source`='"+t_source.getText()+"',`destination`='"+t_destination.getText()+"',`type`='"+t_type.getText()+"',`departure`='"+t_departure.getText()+"',`arrival`='"+t_arrival.getText()+"',`seats_available`='"+t_seatsAvailable.getText()+"',`fare`='"+t_fare.getText()+"', `date`= '"+t_date.getText()+"' WHERE id= '"+t_busID.getText()+"'";
        executeSQLquery(query, "UPDATED");
    }//GEN-LAST:event_t_updateActionPerformed

    private void t_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_deleteActionPerformed
        String query = "DELETE FROM `bus_details` WHERE id ="+t_busID.getText();
        executeSQLquery(query,"DELETED");
    }//GEN-LAST:event_t_deleteActionPerformed

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        setVisible(false);
        adminHome obj= new adminHome(s);
    }//GEN-LAST:event_b_backActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bus_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bus_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bus_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bus_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } */
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bus_details().setVisible(true);
            }
        }); 
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_arrival;
    private javax.swing.JLabel l_busID;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_departure;
    private javax.swing.JLabel l_destination;
    private javax.swing.JLabel l_fair;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_seatsAvailable;
    private javax.swing.JLabel l_source;
    private javax.swing.JLabel l_type;
    private javax.swing.JTextField t_arrival;
    private javax.swing.JTextField t_busID;
    private javax.swing.JTextField t_date;
    private javax.swing.JButton t_delete;
    private javax.swing.JTextField t_departure;
    private javax.swing.JTextField t_destination;
    private javax.swing.JTextField t_fare;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_seatsAvailable;
    private javax.swing.JTextField t_source;
    private javax.swing.JTextField t_type;
    private javax.swing.JButton t_update;
    private javax.swing.JTable table_busDetails;
    // End of variables declaration//GEN-END:variables
}
