/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database;
import bus.ticket.reservation.system.Login;
import bus.ticket.reservation.system.bookingSeat;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Avishek Saha
 */


public class search_details extends javax.swing.JFrame {

    /**
     * Creates new form search_details
     */
    private String fm;
    private String to;
    private String jDate;
    save s;
    
    public search_details(save s,String fm,String to, String jDate) {
        this.s = s;
        
        this.fm=fm;
        this.to=to;
        this.jDate=jDate;
        initComponents();
       
        searchBuses();
       // b_bookSeatsActionPerformed(java.awt.event.ActionEvent evt);
        
    }
    
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/btrs", "root","");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }

    
    public ArrayList<Bus> getBus(){ 
	
		ArrayList<Bus> buses	= new ArrayList<Bus>();
		Connection con = getConnection();
		
		Statement stat;
		ResultSet rs;
		Bus b;
                
              
	
	try{
            
		stat = con.createStatement();
		String sql="select * from bus_details where source ='"+fm+"' and destination = '"+to+"'and date = '"+jDate+"' ";
		rs= stat.executeQuery(sql);
		
		while(rs.next()){
			
			b = new Bus(
			      rs.getInt("id"),
				  rs.getString("name"),
				  rs.getString("source"),
				  rs.getString("destination"),
				  rs.getString("type"),
				  rs.getString("departure"),
				  rs.getString("arrival"),
				  rs.getInt("seats_available"),
				  rs.getInt("fare"),
                                rs.getString("date")
			);
			
			buses.add(b);
		}
	}
	catch (Exception e) {
            e.printStackTrace();          
        }
		
	
	return buses;
}
    
     public void searchBuses()
    {
        ArrayList<Bus> list = getBus();
        DefaultTableModel model = (DefaultTableModel)table_searchDetails.getModel();
        
        Object[] row = new Object[9];
       for(int i = 0; i < list.size(); i++)
       {
           row[0] = list.get(i).getId();
             row[1] = list.get(i).getName();
              row[2] = list.get(i).getSource();
               row[3] = list.get(i).getDestination();
	        row[4] = list.get(i).getType();
	         row[5] = list.get(i).getDeparture();
		  row[6] = list.get(i).getArrival();
		   row[7] = list.get(i).getSeatsAvailable();
				    row[8] = list.get(i).getFare();
           
           model.addRow(row);
       }
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_busID = new javax.swing.JLabel();
        l_source = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_type = new javax.swing.JLabel();
        l_destination = new javax.swing.JLabel();
        l_departure = new javax.swing.JLabel();
        l_arrival = new javax.swing.JLabel();
        l_seatsAvailable = new javax.swing.JLabel();
        l_fare = new javax.swing.JLabel();
        l_jDate = new javax.swing.JLabel();
        t_seatsAvailable = new javax.swing.JTextField();
        t_arrival = new javax.swing.JTextField();
        t_departure = new javax.swing.JTextField();
        t_type = new javax.swing.JTextField();
        t_destination = new javax.swing.JTextField();
        t_source = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_busID = new javax.swing.JTextField();
        t_fare = new javax.swing.JTextField();
        t_jDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_searchDetails = new javax.swing.JTable();
        b_back = new javax.swing.JButton();
        b_bookSeats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l_busID.setText("Bus ID");

        l_source.setText("Source");

        l_name.setText("Bus Name");

        l_type.setText("Type");

        l_destination.setText("Destination");

        l_departure.setText("Departure");

        l_arrival.setText("Arrival");

        l_seatsAvailable.setText("Seats Available");

        l_fare.setText("Fare");

        l_jDate.setText("Journey Date");

        t_seatsAvailable.setEditable(false);

        t_arrival.setEditable(false);

        t_departure.setEditable(false);

        t_type.setEditable(false);

        t_destination.setEditable(false);

        t_source.setEditable(false);

        t_name.setEditable(false);

        t_busID.setEditable(false);

        t_fare.setEditable(false);

        t_jDate.setText(jDate);
        t_jDate.setEditable(false);

        table_searchDetails.setBackground(new java.awt.Color(51, 255, 51));
        table_searchDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "Name", "Source", "Destination", "Type", "Departure", "Arrival", "Seats Available", "Fare"
            }
        ));
        table_searchDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_searchDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_searchDetails);

        b_back.setText("Cancel");
        b_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_backActionPerformed(evt);
            }
        });

        b_bookSeats.setBackground(new java.awt.Color(153, 204, 0));
        b_bookSeats.setForeground(new java.awt.Color(0, 51, 0));
        b_bookSeats.setText("Book Seats");
        b_bookSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bookSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_source, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_seatsAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_jDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(t_seatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(b_bookSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_source, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_source, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_type, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_departure, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_arrival, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_seatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_seatsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_bookSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void table_searchDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_searchDetailsMouseClicked
         // Display Selected Row in JTextFields
        int i = table_searchDetails.getSelectedRow();
        TableModel model = table_searchDetails.getModel();
        
        t_busID.setText(model.getValueAt(i,0).toString());
        t_name.setText(model.getValueAt(i,1).toString());
        t_source.setText(model.getValueAt(i,2).toString());
        t_destination.setText(model.getValueAt(i,3).toString());
        t_type.setText(model.getValueAt(i,4).toString());
        t_departure.setText(model.getValueAt(i,5).toString());
        t_arrival.setText(model.getValueAt(i,6).toString());
        t_seatsAvailable.setText(model.getValueAt(i,7).toString());
        t_fare.setText(model.getValueAt(i,8).toString());
    }//GEN-LAST:event_table_searchDetailsMouseClicked

    private void b_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login obj = new Login();
    }//GEN-LAST:event_b_backActionPerformed

    private void b_bookSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bookSeatsActionPerformed
        setVisible(false);
        bookingSeat book = new bookingSeat(s,t_busID.getText(), t_seatsAvailable.getText(),t_jDate.getText(),t_fare.getText(),t_name.getText(),t_source.getText(),t_destination.getText(),t_type.getText(),t_departure.getText(),t_arrival.getText());
    }//GEN-LAST:event_b_bookSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
   /*    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_details().setVisible(true);
            }
        }); */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_bookSeats;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_arrival;
    private javax.swing.JLabel l_busID;
    private javax.swing.JLabel l_departure;
    private javax.swing.JLabel l_destination;
    private javax.swing.JLabel l_fare;
    private javax.swing.JLabel l_jDate;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_seatsAvailable;
    private javax.swing.JLabel l_source;
    private javax.swing.JLabel l_type;
    private javax.swing.JTextField t_arrival;
    private javax.swing.JTextField t_busID;
    private javax.swing.JTextField t_departure;
    private javax.swing.JTextField t_destination;
    private javax.swing.JTextField t_fare;
    private javax.swing.JTextField t_jDate;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_seatsAvailable;
    private javax.swing.JTextField t_source;
    private javax.swing.JTextField t_type;
    private javax.swing.JTable table_searchDetails;
    // End of variables declaration//GEN-END:variables
}
